name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          pip install huggingface_hub
          python -c "from huggingface_hub import HfApi; api = HfApi(); api.upload_folder(repo_id='${{ secrets.HF_SPACE_ID }}', repo_type='space', folder_path='.', path_in_repo='', token='${{ secrets.HF_TOKEN }}', allow_patterns=['*.py', '*.pt', '*.pkl', '*.txt', '*.md', 'Dockerfile', '**/*.py', '**/*.pt', '**/*.pkl'])" 